version: '3.2'

services:
  api:
    container_name: api
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/api
      - /api/node_modules
    ports:
      - 8081:8081
      - 9229:9229
    command: yarn dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: